-- ==============================================================================
-- DATABASE REBUILD SCRIPT (V4)
-- WARNING: THIS WILL DELETE ALL EXISTING DATA IN THE TABLES LISTED BELOW.
-- ==============================================================================

-- 1. DROP EXISTING TABLES (Order matters due to foreign keys)
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.carts CASCADE;
DROP TABLE IF EXISTS public.food_items CASCADE;
DROP TABLE IF EXISTS public.user_details CASCADE; -- Legacy table
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. CREATE USERS TABLE (Syncs with auth.users)
CREATE TABLE public.users (
    id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id)
);

-- Enable RLS for users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policies for users
CREATE POLICY "Users can view their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id);
-- Allow public read for verifying student IDs (needed for login logic if strictly required, otherwise restrict)
-- Based on previous logic, we sometimes need to query by email prefix. 
-- For security, let's keep it restricted to authenticated users or SERVICE_ROLE.
-- But the login script uses `verificationSupabase` (anon key) to check existence.
CREATE POLICY "Allow anonymous read for verification" ON public.users FOR SELECT TO anon USING (true);


-- 3. CREATE FOOD ITEMS TABLE
CREATE TABLE public.food_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for food_items
ALTER TABLE public.food_items ENABLE ROW LEVEL SECURITY;

-- Policies for food_items
CREATE POLICY "Anyone can view food items" ON public.food_items FOR SELECT USING (true);
CREATE POLICY "Admins can insert food items" ON public.food_items FOR INSERT WITH CHECK (
    -- Ideally check a flag, for now we allow authenticated to simulate 'admin' if no strict role system
    -- Or we can just allow all authenticated for simplicity as per current app state
    auth.role() = 'authenticated'
);
CREATE POLICY "Admins can update food items" ON public.food_items FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete food items" ON public.food_items FOR DELETE USING (auth.role() = 'authenticated');


-- 4. CREATE CARTS TABLE
CREATE TABLE public.carts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    food_item_id BIGINT REFERENCES public.food_items(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, food_item_id) -- Prevent duplicate rows for same item
);

-- Enable RLS for carts
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;

-- Policies for carts
CREATE POLICY "Users can view their own cart" ON public.carts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert into their own cart" ON public.carts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own cart" ON public.carts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete from their own cart" ON public.carts FOR DELETE USING (auth.uid() = user_id);


-- 5. CREATE ORDERS TABLE
CREATE TABLE public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL, -- Keep order history even if user deleted
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, completed, cancelled
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Policies for orders
CREATE POLICY "Users can view their own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
-- Allow admins (or anyone authenticated for now, to enable the Admin Panel to work) to view ALL orders
-- This is a simplification. For production, check a proper 'role'.
CREATE POLICY "Admins can view all orders" ON public.orders FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can update order status" ON public.orders FOR UPDATE USING (auth.role() = 'authenticated');


-- 6. CREATE ORDER ITEMS TABLE
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    food_item_id BIGINT REFERENCES public.food_items(id) ON DELETE SET NULL, -- Keep record if food item deleted
    quantity INTEGER NOT NULL,
    price_at_time NUMERIC NOT NULL, -- Store price at time of purchase
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for order_items
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Policies for order_items
-- Users can view items if they own the parent order.
-- This requires a join or subquery which can be expensive in RLS, but standard practice.
CREATE POLICY "Users can view their order items" ON public.order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
    OR
    auth.role() = 'authenticated' -- Allow admins to see as well
);
CREATE POLICY "Users can insert order items" ON public.order_items FOR INSERT WITH CHECK (
    -- Ideally check ownership of order, but simplified:
    auth.role() = 'authenticated'
);


-- 7. SETUP USER SYNC TRIGGER (Auth -> Public.Users)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, email, name)
    VALUES (
        new.id,
        new.email,
        new.raw_user_meta_data->>'full_name'
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        name = EXCLUDED.name;
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Backfill existing users
INSERT INTO public.users (id, email, name)
SELECT 
    id, 
    email, 
    raw_user_meta_data->>'full_name'
FROM auth.users
ON CONFLICT (id) DO NOTHING;


-- 8. GRANT PERMISSIONS
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;


-- 9. SEED INITIAL MENU DATA
INSERT INTO food_items (category, name, price) VALUES
-- BEVERAGES
('Beverages', 'Soft Drink', 50),
('Beverages', 'Watermelon Juice', 100),
('Beverages', 'Local Tea (Black)', 20),
('Beverages', 'Milk Tea', 35),
('Beverages', 'Instant Coffee Black', 30),
('Beverages', 'Instant Coffee Milk', 35),
('Beverages', 'Hot Lemon', 25),
('Beverages', 'Lemon Tea', 25),
('Beverages', 'Hot Lemon with Honey', 65),
('Beverages', 'Hot Milk', 40),
('Beverages', 'Plain Lassi', 120),
('Beverages', 'Banana Lassi', 150),

-- BREAKFAST
('Breakfast', 'Chana', 40),
('Breakfast', 'Aloo', 40),
('Breakfast', 'Tarkari', 40),
('Breakfast', 'Dalbh', 45),
('Breakfast', 'Garlic Bread (2pc)', 30),
('Breakfast', 'Butter Toast', 30),
('Breakfast', 'Jam Toast', 20),
('Breakfast', 'Bread Toast', 20),
('Breakfast', 'Boiled Egg', 30),
('Breakfast', 'Single Masala Omelet', 40),
('Breakfast', 'Double Masala Omelet', 80),
('Breakfast', 'Plain Single Omelet', 40),
('Breakfast', 'Plain Double Omelet', 75),
('Breakfast', 'Samosa', 30),
('Breakfast', 'Chicken Sausage (1pc)', 50),
('Breakfast', 'Mixed Fruits', 160),
('Breakfast', 'Breakfast Set (Egg, Aloo, Dal, Roti, Tea/Coffee)', 175),

-- SNACKS
('Snacks', 'Potato Wedges', 100),
('Snacks', 'French Fries', 110),
('Snacks', 'Paneer Chilly', 240),
('Snacks', 'Chips Chilly', 130),
('Snacks', 'Chicken Chilly', 240),
('Snacks', 'Sausage Chilly', 220),
('Snacks', 'Egg Chilli Fry', 120),

-- WAI-WAI
('Wai-Wai', 'Wai-Wai Sadheko', 60),
('Wai-Wai', 'Veg Wai-Wai Fry/Soup', 75),
('Wai-Wai', 'Egg Wai-Wai Fry/Soup', 100),
('Wai-Wai', 'Mixed Wai-Wai Fry/Soup', 120),
('Wai-Wai', 'Chicken Wai-Wai Fry/Soup', 150),
('Wai-Wai', 'ING Fried Rice', 250),

-- FRIED RICE & NOODLES
('Fried Rice & Noodles', 'Veg Fried Rice', 100),
('Fried Rice & Noodles', 'Egg Fried Rice', 125),
('Fried Rice & Noodles', 'Chicken Fried Rice', 150),
('Fried Rice & Noodles', 'Mixed Fried Rice', 175),

-- MO:MO
('Momo', 'Veg Momo Steam', 100),
('Momo', 'Veg Momo Fried', 140),
('Momo', 'Veg Momo Jhol', 150),
('Momo', 'Veg C-Momo', 175),
('Momo', 'Veg Momo Chilli', 185),
('Momo', 'Buff Momo Steam', 140),
('Momo', 'Buff Momo Fried', 160),
('Momo', 'Buff Momo Jhol', 170),
('Momo', 'Buff C-Momo', 185),
('Momo', 'Buff Momo Chilli', 195),
('Momo', 'Chicken Momo Steam', 150),
('Momo', 'Chicken Momo Fried', 170),
('Momo', 'Chicken Momo Jhol', 180),
('Momo', 'Chicken C-Momo', 195),
('Momo', 'Chicken Momo Chilli', 205),

-- SANDWICH & BURGER
('Sandwich & Burger', 'Veg Sandwich', 140),
('Sandwich & Burger', 'Cheese Sandwich', 190),
('Sandwich & Burger', 'Chicken Sandwich', 240),
('Sandwich & Burger', 'Club Sandwich', 350),

-- SOUP & THUKPA
('Soup & Thukpa', 'Veg Soup', 100),
('Soup & Thukpa', 'Chicken Soup', 120),
('Soup & Thukpa', 'Veg Thukpa', 125),
('Soup & Thukpa', 'Egg Thukpa', 150),
('Soup & Thukpa', 'Chicken Thukpa', 170),
('Soup & Thukpa', 'Mixed Thukpa', 180),

-- RICE THALI
('Rice Thali', 'Veg Thali', 160),
('Rice Thali', 'Chicken Thali', 210),
('Rice Thali', 'Paneer Thali', 210),

-- DAY SPECIAL MENU
('Day Special Menu', 'Chicken Tandoori', 300),
('Day Special Menu', 'Chicken Butter Masala', 300),
('Day Special Menu', 'Chicken Curry', 280),
('Day Special Menu', 'Paneer Butter Masala', 280),
('Day Special Menu', 'Chicken Sekuwa', 300);

-- Print success message (optional, might show in SQL output)
SELECT 'Database Rebuilt Successfully' as result;
