-- Run this in your Supabase SQL Editor to create the table
CREATE TABLE IF NOT EXISTS public.user_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL, -- 'student' or 'staff'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.user_details ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (Required for the import script to work with the anon key)
CREATE POLICY "Allow public inserts" 
ON public.user_details 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Allow anonymous selects (Optional, for verification)
CREATE POLICY "Allow public read" 
ON public.user_details 
FOR SELECT 
TO anon 
USING (true);
